services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: marksuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb
    # Pre-seed script is required as a volume to load mock database
    # Data inside the container is lost on restart unless you persist it with a volume.
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: "db"
      DB_NAME: "marksdb"
      DB_USER: "marksuser"
      DB_PASSWORD: "markspass"
    ports: 
      - "5000:5000"
    # TODO: you will need to add to this

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # TODO: you will need to add to this

  automark:
    build: ./automark
    depends_on:
      - backend
      - db
    profiles:
      - debug

volumes:
  db-volume: 
